version: "3.9"

services:
  db:
    image: postgres:16
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: recursive-query-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
